08/May/2017:20:33:31 +0800 [ERROR 502 /api/user] dial tcp [::1]:9090: connectex: No connection could be made because the target machine actively refused it.
08/May/2017:20:34:57 +0800 [ERROR 502 /api/user] dial tcp [::1]:9090: connectex: No connection could be made because the target machine actively refused it.
08/May/2017:20:35:28 +0800 [ERROR 502 /api/user] dial tcp [::1]:9090: connectex: No connection could be made because the target machine actively refused it.
08/May/2017:20:35:36 +0800 [ERROR 502 /api/user] dial tcp [::1]:9090: connectex: No connection could be made because the target machine actively refused it.
08/May/2017:20:37:56 +0800 [ERROR 502 /api/user] dial tcp [::1]:9090: connectex: No connection could be made because the target machine actively refused it.
08/May/2017:20:38:08 +0800 [ERROR 502 /api/user] dial tcp [::1]:9090: connectex: No connection could be made because the target machine actively refused it.
08/May/2017:21:00:31 +0800 [ERROR 502 /api/user] dial tcp [::1]:9090: connectex: No connection could be made because the target machine actively refused it.
17/May/2017:08:18:56 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:50 - runtime error: slice bounds out of range
17/May/2017:08:19:08 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:50 - runtime error: slice bounds out of range
17/May/2017:08:19:09 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:50 - runtime error: slice bounds out of range
17/May/2017:08:21:15 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:52 - runtime error: slice bounds out of range
17/May/2017:08:23:32 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:53 - runtime error: slice bounds out of range
17/May/2017:08:27:15 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:57 - runtime error: slice bounds out of range
17/May/2017:08:27:17 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:57 - runtime error: slice bounds out of range
17/May/2017:08:27:17 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:57 - runtime error: slice bounds out of range
17/May/2017:08:36:36 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:51 - runtime error: slice bounds out of range
17/May/2017:08:39:11 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:51 - runtime error: slice bounds out of range
17/May/2017:08:41:16 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:52 - runtime error: slice bounds out of range
17/May/2017:08:42:02 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:52 - runtime error: slice bounds out of range
17/May/2017:08:43:17 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:52 - runtime error: slice bounds out of range
17/May/2017:08:50:07 +0800 [PANIC /api/user] D:/go_workspace/src/utils/caddyutil/validatetoken.go:49 - runtime error: slice bounds out of range
